### PR TITLE
Add a section about persisting data

### LINKED ISSUE #72: Best practices regarding to data storage
I think it would be good if there were some information regarding to data storing, like:
- best practices when writing Content Providers
- when to use Shared Preferences
- ORMs, do and don't

### PR DESCRIPTION
**Pull request by tehmou**
General guidelines for choosing a data persistence strategy.

resolves #72

### CODE REVIEW

**Comment by aziflaj** [comment]
Thanks :smile: 
Between [Schematic](https://github.com/SimonVT/schematic) and [ProviGen](https://github.com/TimotheeJeannin/ProviGen), which one would you recommend?

**Comment by staltz** [comment]
Looks great to me

**Comment by tremerhl** [comment]
If you don't need anything complicated, [Simple Provider](https://github.com/Triple-T/simpleprovider) is a great choice.

**Comment by tehmou** [comment]
@aziflaj I have personally had good experiences with Schematic, hence mentioning it. I like that it is precompiled, as annotations are known to be slow on Dalvik. You can also easily inspect the resulting source code, which is just a typical ContentProvider. I did not try ProviGen yet, though it seems to be different in its approach of extending the library base classes.

@tremerhl do you know how mature the Simple Provider is?

**Comment by tremerhl** [comment]
@tehmou  SimpleProvider is pretty young library, it also uses annotations to create database, hence you need to add `-keep` to your ProGuard. I've had good experience using it to create and interact with one db table, can't say anything with respect to it's efficiency with really complex data.

**Comment by SMontiel** [comment]
I like ActiveAndroid

**Pull request merged**
