### PR TITLE
Set important constants in build.gradle

### PR DESCRIPTION
**Pull request by tremerhl**

### CODE REVIEW

**Comment by bryant1410** [comment]
What's the benefit of having keys in the `build.gradle` file?

Also, a problem that arises is that they will end up being versioned, which this is sometimes not desired.

**Comment by tremerhl** [comment]
Benefit is that you are able to define single constant with different values for release/debug/other build types and then easily access it when providing dagger dependencies.

**Comment by bryant1410** [comment]
You can use string resources for different flavors and release/debug too. What do you mean by "easily access it when providing dagger dependencies"?

**Comment by tremerhl** [comment]
I mean access it from inside the module instead of passing it to module constructor

**Comment by bryant1410** [comment]
Do you mean Dagger 2 modules? I still don't see the point and what it has to do with defining constants.

**Comment by tremerhl** [comment]
Correct, Dagger 2

**Pull request closed without merging**
