### PR TITLE
Feature: Add assertion test framework best practice for Android using AssertJ-Android

### PR DESCRIPTION
**Pull request by KevinLeighCrain**
@futurice Hey there! I have added best practices on asserting Android specific components in Android tests. Let me know what you like and your reasoning if you don't. Thanks!

### CODE REVIEW

**Comment by Tony---Zhang** [comment]
I prefer AssertJ too~

**Comment by peter-tackage** [comment]
I'm also an AssertJ fan, I had it somewhere in my mind to include a reference to it in an updated testing section (that section is *really* dated now). I'd be inclined to mention that the key point is that there are libraries out there to make more powerful assertions (also note: https://github.com/google/truth)

**Comment by KevinLeighCrain** [comment]
@peter-tackage Thanks for the response, you are correct about Truth, and for me personally keeping your projects to use purely Google dependencies is a big yes. I have recently stumbled across Truth and found it very similar to using AssertJ (both using Hamcrest matchers). I have not noticed Truth power yet with Android, as I find AssertJ-Android is currently more geared towards Android. I would love to help adding Android specific extensions to Truth, it is however a big task and not a days work with my current schedule.


Lastly please could you post back the link to the up to date testing section so I may familiarize myself with it. Much appreciated.

**Comment by peter-tackage** [comment]
I don't know if I'd go as far as advocating Google-only dependencies. Google can still be quite fickle with some of their non-official Android / Java libraries. Picking future trend or winners in libraries is a difficult task; having a big name backer is one dimension, but certainly no guarantee. Is anyone using Agera rather than RxJava?

**Comment by KevinLeighCrain** [comment]
@peter-tackage It is definitely a difficult task picking libraries as there is so many out there mostly bad but a lot of good ones, and my reasoning behind pure Google dependencies is that Google is there to stay, I am however open minded to try anything new, going to look at Agera, and try it out definitely! Thanks for the mention!

**Pull request merged**
